prune_type: "l0"
start_sparsity: 0.0
target_sparsity: 0.5
pruning_modules: ["hidden"]
lagrangian_warmup_steps: 2560
target_model:
  hidden_size: 2560
  num_attention_heads: 40 
  ffn_hidden_size: 11008 
  encoder_num_layers: 12
  decoder_num_layers: 36
eval_target_model: True